spring: 
  profiles: 
    active: 
    - dev
---

server:
  port: 8001
  # mybatis 配置
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml                      #mybatis配置文件所在路径
#  mapper-locations: classpath*:/mapper/*Mapper.xml                   #mapper 的映射文件
#  type-aliases-package: com.sd.springcloud.bean                              # 实体类所在的包
# mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml                      #mybatis配置文件所在路径
  mapper-locations: classpath*:/mapper/*Mapper.xml                   #mapper 的映射文件
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.sd.springcloud.bean                              # 实体类所在的包
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true
spring:
  profiles: dev
  application:
    name: sd-springcloud-config-provider-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://47.106.196.94:3306/dian?useUnicode=true&characterEncoding=utf-8&useSSL=false       #链接地址，数据库名称
    username: root
    password: Midian0612***
    dbcp2:
      min-idle: 5                                    #数据库连接池的最小维持连接数
      initial-size: 5                                #初始化连接数
      max-total: 5                                   #最大连接数
      max-wait-millis: 200                           #等待连接获取的最大超时时间
#注册中心地址
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
#    instance-id: sd-springcloud-8001   # 微服务别名
    instance-id: sd-springcloud-config-provider-client   # 微服务别名
    prefer-ip-address: true  #访问路径可以显示ip

info:
  app.name: sd-springcloud-config-provider-client
  company.name: www.shuaidian.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
  
---

server:
  port: 8001
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml                      #mybatis配置文件所在路径
  mapper-locations: classpath*:/mapper/*Mapper.xml                   #mapper 的映射文件
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.sd.springcloud.bean                              # 实体类所在的包
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true
spring:
  profiles: test
  application:
    name: sd-springcloud-config-provider-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://47.106.196.94:3306/dian_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false       #链接地址，数据库名称
    username: root
    password: Midian0612***
    dbcp2:
      min-idle: 5                                    #数据库连接池的最小维持连接数
      initial-size: 5                                #初始化连接数
      max-total: 5                                   #最大连接数
      max-wait-millis: 200                           #等待连接获取的最大超时时间
#注册中心地址
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
#    instance-id: sd-springcloud-8001   # 微服务别名
    instance-id: sd-springcloud-config-provider-client  # 微服务别名
    prefer-ip-address: true  #访问路径可以显示ip

info:
  app.name: sd-springcloud-config-provider-client
  company.name: www.shuaidian.top
  build.artifactId: $project.artifactId$
  build.version: $project.version$